# This is a basic workflow to help you get started with Actions

name: CI - Test&Build

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
# Set variables
#env:
#  GH_WS: $env:GITHUB_WORKSPACE

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    permissions: write-all
    # The type of runner that the job will run on
    runs-on: self-hosted
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
      
      # Start LabVIEW and wait for it to start to avoid timeout issues in following steps
      - name: Start LabVIEW
        run: Start-Process "C:\Program Files\National Instruments\LabVIEW 2023\LabVIEW.exe"
        run: sleep 30
      
      # Run Unit Tests before executable build
      - name: LabVIEW Caraya Unit Tests
        run: LabVIEWCLI -OperationName RunVI -VIPath ".\Source\Pre-Build\RunCL - Run All Tests.vi" -PortNumber 3364
      
      # Test report upload
      - name: Test Report
        uses: dorny/test-reporter@v2
        if: success() || failure()                  # run this step even if previous step failed
        with:
          name: LabVIEW Tests                       # Name of the check run which will be created
          path: Source/test-results/**/*.xml        # Path to test results
          reporter: java-junit                      # Format of test results
            
      # Build LabVIEW Executable via LabVIEWCLI
      - name: LabVIEW Build
        #shell: pwsh
        run: LabVIEWCLI -LogToConsole true -OperationName ExecuteBuildSpec -ProjectPath ".\source\LV_Calculator.lvproj" -BuildSpecName "LV_Calculator" -LabVIEWPath "C:\Program Files\National Instruments\LabVIEW 2023\LabVIEW.exe" -PortNumber 3364
   
