name: Build LabVIEW Packed Library via Local Action

on:
  push:
    branches: [ "main" ]
    
  workflow_dispatch:

jobs:
  
  build_lvlibp:
    runs-on: [self-hosted, windows, x64, runner-2]

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4
      
      - name: Configure LabVIEW for Remote Access
        uses: perhed-dvel/open-source/configure-labview@per-dev
        with:
          # Optional
          labview_version: 2026
          ini_settings: |
              server.tcp.enabled=TRUE
              server.tcp.access=+*
              server.tcp.port=3363
              server.viscripting.ShowScriptingOperationsInEditor=TRUE

      - name: Run Build Spec Docker Windows Action
        uses: perhed-dvel/open-source/build-spec-docker-windows@per-dev
        with:
          # Mandatory
          minimum_supported_lv_version: 2026
          supported_bitness: 64
          project_path: 'Source\LV_Calculator.lvproj'
          
          # Optional
          docker_image: 'prevas/labview'
          image_tag: '2026q3-windows-ci1'
          build_spec_name: 'Functions'
